config:
  dockerfile: .woloxci/Dockerfile
  project_name: conduit-react

steps:
  lint:
    - npm run ts-check
    - npm run lint
    - npm run lint-scss

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
