config:
  dockerfile: .woloxci/Dockerfile
  project_name: conduit-react

steps:
  cypress:
    - . /home/node/.profile
    - chown -R 498:0  $(npm config get prefix)
    - chown -R 498:0  /home/node/
    - npx cypress run
  lint:
    - ln -sfn /home/node/node_modules node_modules
    - npm run ts-check
    - npm run lint
    - npm run lint-scss
    
environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
