config:
  dockerfile: .woloxci/Dockerfile
  project_name: conduit-react

steps:
  cypress:
    - ln -sfn /home/node/node_modules node_modules
    - . /home/node/.profile
    - rm package-lock.json
    - rm -r node_modules
    - npm cache clean --force
    - npm install cypress --save-dev
    - npx cypress run
  lint:
    - npm run ts-check
    - npm run lint
    - npm run lint-scss
    
environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
