config:
  dockerfile: .woloxci/Dockerfile
  project_name: conduit-react
  
cache:
  directories:
  - "$HOME/.cache/Cypress"

steps:
  cypress:
    - ln -sfn /home/node/node_modules node_modules
    - node_modules/cypress/bin/cypress run
  lint:
    - npm run ts-check
    - npm run lint
    - npm run lint-scss

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
