name: CI

on:
  push:
    branches: [ feature/cypress-on-dockerfile ]
  pull_request:
    branches: [ feature/cypress-on-dockerfile ]

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
